name: "Release"
on:
  push:
    branches:
      - master
jobs:
  release_job:
    runs-on: macOS
    name: "Build Zeplin Client"
    steps:
      - name: "Source code checkout"
        uses: actions/checkout@v1
      - name: "Build application using fastlane"
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: "build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
